[package]
name = "pso"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
simple_logger = "5.0.0"
log = "0.4.22"
image = "0.25.5"
imageproc = { version = "0.25.0", features = ["rayon"] }
gif = "0.13.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
